qc_pipeline:
  output_dir: "/scratch/14196861/projetos/gemeos_xpv/results/Anotados/summary/summary-exclusivos"
  samplesheet: "/scratch/14196861/projetos/gemeos_xpv/summary/samples.tsv"
  
  dp_field: "DP"
  af_field: "AF"
  
  dp_color: "royalblue"
  af_color: "salmon"  

  html_filename: "Relatorio_Exclusivas_Gemeos_XPV.html"  # Nome do arquivo gerado
  report_title: "Gêmeos XPV - Exclusivas)" # Título que aparece no topo da página
